apiVersion: v1
kind: Service
metadata:
  name: postgresql-headless
  namespace: personal-project
  labels:
    app: postgresql
spec:
  clusterIP: None
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql